### ISSUE TITLE
Brilliant work.. Nothing like this module out there..

### ISSUE THREAD

**Issue by ericmaro** [zainozzaini/react-native-android-image-cropper#1]
Can you add Some effects like saturation, black and white,(scan effects)? again thank you for sharing this..

**Comment by zainozzaini** [comment]
Hi.. currently im not planning on extended the core native module function to other features. Im focusing on extent it to be used on RN. The native library that used is from ArthurHub/Android-Image-Cropper  - https://github.com/ArthurHub/Android-Image-Cropper
